### ISSUE TITLE
*ix: Should system libraries be included?

### ISSUE THREAD

**Issue by sciurius** [shawnlaffan/perl-pp-autolink#15]
On *ix (ldd) systems, libraries that reside in the system location (/lib, /lib64 etc.) are not included. While this makes sense for libraries like libc, non-standard libraries (e.g. libcurl, libsndfile, libMagick, ...) will be missing in the executable and the program can not be run on a system that doesn't have these libraries installed.

Wouldn't it make more sense to include all system libraries with the exception of libc and libm?

**Comment by shawnlaffan** [comment]
True.  I've changed it to pack all except libm, libc, libpthread and libdl.  

The CI failures have been cleared up in separate commits.

**Comment by shawnlaffan** [comment]
version 2.05 is now on CPAN
